// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: ESP32_GPX

#ifndef _ESP32_GPX_UI_H
#define _ESP32_GPX_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"
#include "ui_page_stack.h"


///////////////////// SCREENS ////////////////////

#include "ui_desktop_page.h"
#include "ui_top.h"
#include "ui_setting.h"

///////////////////// VARIABLES ////////////////////


// EVENTS


// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
