// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: ESP32_GPX

#include "ui.h"

lv_obj_t * ui_Screen1;
lv_obj_t * ui_Latitude;
lv_obj_t * ui_Longitude;
lv_obj_t * ui_TextArea2;
lv_obj_t * ui_LatitudeValue;
lv_obj_t * ui_LongitudeValue;
lv_obj_t * ui_Altitude;
lv_obj_t * ui_AltitudeValue;
lv_obj_t * ui_Speed;
lv_obj_t * ui_SpeedValue;
lv_obj_t * ui_NumberOfSatellites;
lv_obj_t * ui_NumberOfSatellitesValue;
lv_obj_t * ui_Azimuth;
lv_obj_t * ui_AzimuthValue;
lv_obj_t * ui_UTC_Date;
lv_obj_t * ui_Date;
lv_obj_t * ui_DateValue;
lv_obj_t * ui_Time;
lv_obj_t * ui_TimeValue;
lv_obj_t * ui_Switch1;

// event funtions

// build funtions

void ui_Screen1_screen_init(lv_obj_t * parent)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t* menu = lv_menu_create(ui_Screen1);
    lv_obj_set_size(menu, LV_PCT(100), LV_PCT(100));
    lv_obj_center(menu);

    lv_obj_t* title = lv_label_create(menu);
    lv_label_set_text(title, "Settings");

    //lv_obj_t* list = lv_obj_create(ui_Screen1);
    //lv_obj_set_height(list, LV_PCT(100));
    //lv_obj_set_style_max_height(list, 300, 0);

    //lv_obj_set_flex_flow(list, LV_FLEX_FLOW_COLUMN);
    //lv_obj_set_flex_grow(list, 1);
    //lv_obj_add_flag(list, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);

    //lv_obj_t * title = lv_label_create(list);
    //lv_label_set_text(title, "Top products");

    //ui_Latitude = lv_label_create(ui_Screen1);
    //lv_obj_set_width(ui_Latitude, LV_SIZE_CONTENT);   /// 1
    //lv_obj_set_height(ui_Latitude, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_x(ui_Latitude, 20);
    //lv_obj_set_y(ui_Latitude, 15);
    //lv_label_set_text(ui_Latitude, "Latitude");
    //lv_obj_set_style_text_font(ui_Latitude, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    //ui_Longitude = lv_label_create(ui_Screen1);
    //lv_obj_set_width(ui_Longitude, LV_SIZE_CONTENT);   /// 1
    //lv_obj_set_height(ui_Longitude, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_x(ui_Longitude, 20);
    //lv_obj_set_y(ui_Longitude, 40);
    //lv_label_set_text(ui_Longitude, "Longitude");
    //lv_obj_set_style_text_font(ui_Longitude, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    //ui_TextArea2 = lv_textarea_create(ui_Screen1);
    //lv_obj_set_width(ui_TextArea2, 150);
    //lv_obj_set_height(ui_TextArea2, 70);
    //lv_obj_set_x(ui_TextArea2, 110);
    //lv_obj_set_y(ui_TextArea2, -41);
    //lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    //lv_textarea_set_placeholder_text(ui_TextArea2, "Placeholder...");
    //lv_obj_add_flag(ui_TextArea2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    //ui_LatitudeValue = lv_label_create(ui_Screen1);
    //lv_obj_set_width(ui_LatitudeValue, LV_SIZE_CONTENT);   /// 1
    //lv_obj_set_height(ui_LatitudeValue, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_x(ui_LatitudeValue, 130);
    //lv_obj_set_y(ui_LatitudeValue, 15);
    //lv_label_set_text(ui_LatitudeValue, "000.000000");
    //lv_obj_set_style_text_font(ui_LatitudeValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    //ui_LongitudeValue = lv_label_create(ui_Screen1);
    //lv_obj_set_width(ui_LongitudeValue, LV_SIZE_CONTENT);   /// 1
    //lv_obj_set_height(ui_LongitudeValue, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_x(ui_LongitudeValue, 130);
    //lv_obj_set_y(ui_LongitudeValue, 40);
    //lv_label_set_text(ui_LongitudeValue, "000.000000");
    //lv_obj_set_style_text_font(ui_LongitudeValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    //ui_Altitude = lv_label_create(ui_Screen1);
    //lv_obj_set_width(ui_Altitude, LV_SIZE_CONTENT);   /// 1
    //lv_obj_set_height(ui_Altitude, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_x(ui_Altitude, 20);
    //lv_obj_set_y(ui_Altitude, 65);
    //lv_label_set_text(ui_Altitude, "Altitude");
    //lv_obj_set_style_text_font(ui_Altitude, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    //ui_AltitudeValue = lv_label_create(ui_Screen1);
    //lv_obj_set_width(ui_AltitudeValue, LV_SIZE_CONTENT);   /// 1
    //lv_obj_set_height(ui_AltitudeValue, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_x(ui_AltitudeValue, 130);
    //lv_obj_set_y(ui_AltitudeValue, 65);
    //lv_label_set_text(ui_AltitudeValue, "0.0000");
    //lv_obj_set_style_text_font(ui_AltitudeValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    //ui_Speed = lv_label_create(ui_Screen1);
    //lv_obj_set_width(ui_Speed, LV_SIZE_CONTENT);   /// 1
    //lv_obj_set_height(ui_Speed, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_x(ui_Speed, 20);
    //lv_obj_set_y(ui_Speed, 90);
    //lv_label_set_text(ui_Speed, "Speed");
    //lv_obj_set_style_text_font(ui_Speed, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    //ui_SpeedValue = lv_label_create(ui_Screen1);
    //lv_obj_set_width(ui_SpeedValue, LV_SIZE_CONTENT);   /// 1
    //lv_obj_set_height(ui_SpeedValue, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_x(ui_SpeedValue, 130);
    //lv_obj_set_y(ui_SpeedValue, 90);
    //lv_label_set_text(ui_SpeedValue, "0.0000");
    //lv_obj_set_style_text_font(ui_SpeedValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    //ui_NumberOfSatellites = lv_label_create(ui_Screen1);
    //lv_obj_set_width(ui_NumberOfSatellites, LV_SIZE_CONTENT);   /// 1
    //lv_obj_set_height(ui_NumberOfSatellites, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_x(ui_NumberOfSatellites, 20);
    //lv_obj_set_y(ui_NumberOfSatellites, 115);
    //lv_label_set_text(ui_NumberOfSatellites, "NumberOfSatellites");
    //lv_obj_set_style_text_font(ui_NumberOfSatellites, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    //ui_NumberOfSatellitesValue = lv_label_create(ui_Screen1);
    //lv_obj_set_width(ui_NumberOfSatellitesValue, LV_SIZE_CONTENT);   /// 1
    //lv_obj_set_height(ui_NumberOfSatellitesValue, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_x(ui_NumberOfSatellitesValue, 220);
    //lv_obj_set_y(ui_NumberOfSatellitesValue, 115);
    //lv_label_set_text(ui_NumberOfSatellitesValue, "0");
    //lv_obj_set_style_text_font(ui_NumberOfSatellitesValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    //ui_Azimuth = lv_label_create(ui_Screen1);
    //lv_obj_set_width(ui_Azimuth, LV_SIZE_CONTENT);   /// 1
    //lv_obj_set_height(ui_Azimuth, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_x(ui_Azimuth, 20);
    //lv_obj_set_y(ui_Azimuth, 140);
    //lv_label_set_text(ui_Azimuth, "Azimuth");
    //lv_obj_set_style_text_font(ui_Azimuth, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    //ui_AzimuthValue = lv_label_create(ui_Screen1);
    //lv_obj_set_width(ui_AzimuthValue, LV_SIZE_CONTENT);   /// 1
    //lv_obj_set_height(ui_AzimuthValue, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_x(ui_AzimuthValue, 130);
    //lv_obj_set_y(ui_AzimuthValue, 140);
    //lv_label_set_text(ui_AzimuthValue, "000.000000");
    //lv_obj_set_style_text_font(ui_AzimuthValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    //ui_UTC_Date = lv_label_create(ui_Screen1);
    //lv_obj_set_width(ui_UTC_Date, LV_SIZE_CONTENT);   /// 1
    //lv_obj_set_height(ui_UTC_Date, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_x(ui_UTC_Date, 20);
    //lv_obj_set_y(ui_UTC_Date, 165);
    //lv_label_set_text(ui_UTC_Date, "UTC Date");
    //lv_obj_set_style_text_font(ui_UTC_Date, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    //ui_Date = lv_label_create(ui_Screen1);
    //lv_obj_set_width(ui_Date, LV_SIZE_CONTENT);   /// 1
    //lv_obj_set_height(ui_Date, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_x(ui_Date, 20);
    //lv_obj_set_y(ui_Date, 190);
    //lv_label_set_text(ui_Date, "Date");
    //lv_obj_set_style_text_font(ui_Date, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    //ui_DateValue = lv_label_create(ui_Screen1);
    //lv_obj_set_width(ui_DateValue, LV_SIZE_CONTENT);   /// 1
    //lv_obj_set_height(ui_DateValue, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_x(ui_DateValue, 130);
    //lv_obj_set_y(ui_DateValue, 190);
    //lv_label_set_text(ui_DateValue, "2000/01/01");
    //lv_obj_set_style_text_font(ui_DateValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    //ui_Time = lv_label_create(ui_Screen1);
    //lv_obj_set_width(ui_Time, LV_SIZE_CONTENT);   /// 1
    //lv_obj_set_height(ui_Time, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_x(ui_Time, 20);
    //lv_obj_set_y(ui_Time, 215);
    //lv_label_set_text(ui_Time, "Time\n");
    //lv_obj_set_style_text_font(ui_Time, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    //ui_TimeValue = lv_label_create(ui_Screen1);
    //lv_obj_set_width(ui_TimeValue, LV_SIZE_CONTENT);   /// 1
    //lv_obj_set_height(ui_TimeValue, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_x(ui_TimeValue, 130);
    //lv_obj_set_y(ui_TimeValue, 215);
    //lv_label_set_text(ui_TimeValue, "00:00:00");
    //lv_obj_set_style_text_font(ui_TimeValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    //ui_Switch1 = lv_switch_create(ui_Screen1);
    //lv_obj_set_width(ui_Switch1, 50);
    //lv_obj_set_height(ui_Switch1, 25);
    //lv_obj_set_x(ui_Switch1, 380);
    //lv_obj_set_y(ui_Switch1, 40);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Latitude = NULL;
    ui_Longitude = NULL;
    ui_TextArea2 = NULL;
    ui_LatitudeValue = NULL;
    ui_LongitudeValue = NULL;
    ui_Altitude = NULL;
    ui_AltitudeValue = NULL;
    ui_Speed = NULL;
    ui_SpeedValue = NULL;
    ui_NumberOfSatellites = NULL;
    ui_NumberOfSatellitesValue = NULL;
    ui_Azimuth = NULL;
    ui_AzimuthValue = NULL;
    ui_UTC_Date = NULL;
    ui_Date = NULL;
    ui_DateValue = NULL;
    ui_Time = NULL;
    ui_TimeValue = NULL;
    ui_Switch1 = NULL;

}
