// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: ESP32_GPX

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(lv_obj_t* parent);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Latitude;
extern lv_obj_t * ui_Longitude;
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_LatitudeValue;
extern lv_obj_t * ui_LongitudeValue;
extern lv_obj_t * ui_Altitude;
extern lv_obj_t * ui_AltitudeValue;
extern lv_obj_t * ui_Speed;
extern lv_obj_t * ui_SpeedValue;
extern lv_obj_t * ui_NumberOfSatellites;
extern lv_obj_t * ui_NumberOfSatellitesValue;
extern lv_obj_t * ui_Azimuth;
extern lv_obj_t * ui_AzimuthValue;
extern lv_obj_t * ui_UTC_Date;
extern lv_obj_t * ui_Date;
extern lv_obj_t * ui_DateValue;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_TimeValue;
extern lv_obj_t * ui_Switch1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

